# Previous pane shortcut
bind -T prefix k select-pane -t :.-
# Kill pane shortcut
bind -T prefix X kill-pane
# Kill session shortcut
bind -T prefix W kill-session

# Pane resize shortcuts
bind -r -T prefix H resize-pane -L 2
bind -r -T prefix J resize-pane -D 2
bind -r -T prefix K resize-pane -U 2
bind -r -T prefix L resize-pane -R 2

setw -g mode-keys vi
