# Previous pane shortcut
bind -T prefix k select-pane -t :.-
# Kill pane shortcut
bind -T prefix X kill-pane
# Kill session shortcut
bind -T prefix W kill-session

# Pane resize shortcuts
bind -r -T prefix H resize-pane -L 2
bind -r -T prefix J resize-pane -D 2
bind -r -T prefix K resize-pane -U 2
bind -r -T prefix L resize-pane -R 2

# Vi navigation & motions
set-window-option -g mode-keys vi

# Vi copy mode shortcuts & macOS clipboard integration
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Clear right of status bar
set -g status-right ""

# Gray out inactive panes
set -g window-style 'bg=colour233'
set -g window-active-style 'bg=black'

# Show ZOOMED in pane border
set-option -g pane-border-format " #{?window_zoomed_flag,#[fg=red bold]ZOOMED,#{pane_current_command}} "

# Add red border around zoomed pane
set-hook -g window-layout-changed 'if -F "#{window_zoomed_flag}" \
  "set -g pane-border-status top; set -g pane-active-border-style fg=red" \
  "set -g pane-border-status off; set -g pane-active-border-style fg=default"'
